parameters:
    produits_manager_service_class: Ecommerce\EcommerceBundle\Services\ProduitsManager
    panier_manager_service_class: Ecommerce\EcommerceBundle\Services\PanierManager
    facture_manager_service_class: Ecommerce\EcommerceBundle\Services\FactureManager
    get_reference_facture_service_class: Ecommerce\EcommerceBundle\Services\GetReference
    generate_facture_to_pdf_service_class: Ecommerce\EcommerceBundle\Services\GenerateFacturePdf
    utilisateurs_session_livraison_service.class: Ecommerce\EcommerceBundle\Services\LivraisonOnSession
    utilisateurs_adresses_handler.class: Ecommerce\EcommerceBundle\Services\UtilisateursAdressesHandler
    tva_twig_extension_class: Ecommerce\EcommerceBundle\Twig\TvaExtension
    tva_montant_twig_extension_class: Ecommerce\EcommerceBundle\Twig\TvaTotalExtension
    redirect_listner_class: Ecommerce\EcommerceBundle\EventListener\RedirectionListener
    utilisateurs_adresses_type.class: Ecommerce\EcommerceBundle\Form\UtilisateursAdressesType
    utilisateurs_adresses_entity.class: Ecommerce\EcommerceBundle\Entity\UtilisateursAdresses
    send.mail.service.class: Ecommerce\EcommerceBundle\Services\MailService
    symfony.form.class: Symfony\Component\Form\Form

services:
    produits_manager_service:
        class: "%produits_manager_service_class%"
        arguments: ["@doctrine.orm.default_entity_manager", "@security.token_storage"]
    panier_manager_service:
        class: "%panier_manager_service_class%"
        arguments: ["@doctrine.orm.default_entity_manager", "@security.token_storage","@request_stack", "@produits_manager_service"]
    facture_manager_service:
        class: "%facture_manager_service_class%"
        arguments: ["@doctrine.orm.default_entity_manager","@request_stack"]
    get_reference_facture_service:
         class: "%get_reference_facture_service_class%"
         arguments: ["@doctrine.orm.default_entity_manager","@security.token_storage"]
    generate_facture_to_pdf_service:
         class: "%generate_facture_to_pdf_service_class%"
         arguments: ["@doctrine.orm.default_entity_manager","@security.token_storage","@html2pdf_factory","@router","@templating"]
    tva_twig_extension:
        class:  "%tva_twig_extension_class%"
        arguments: []
        tags:
            -  { name: twig.extension }
    tva_montant_twig_extension:
        class:  "%tva_montant_twig_extension_class%"
        arguments: []
        tags:
            -  { name: twig.extension }
    redirect_listner:
        class:  "%redirect_listner_class%"
        arguments: ["@security.token_storage", "@router","@panier_manager_service"]
        tags:
            -  { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    userad_form:
        class: "%symfony.form.class%"
        factory: ["@form.factory",createNamed]
        arguments:
            - adresseU
            - '%utilisateurs_adresses_type.class%'
#            - userad_form
#    utilisateurs_adresses_type:
#        class: "%utilisateurs_adresses_type.class%"
#        tags:
#            - { name: form.type, alias: userad_former }
    utilisateurs_adresses_handler:
        class: "%utilisateurs_adresses_handler.class%"
        arguments: ["@form.factory","@request_stack", "@doctrine.orm.default_entity_manager", "@security.token_storage","@userad_form","@event_dispatcher"]
    utilisateurs_session_livraison_service:
        class: "%utilisateurs_session_livraison_service.class%"
        arguments: ["@request_stack", "@doctrine.orm.default_entity_manager", "@security.token_storage","@router"]
    ecommerce_listner_new_event:
        class: Ecommerce\EcommerceBundle\EventListener\UcAdressePaysListener
        arguments: ["@request_stack"]
        tags:
            - { name: kernel.event_listener, event: ecommerce_events.adresse_pays , method: processMessage }
    oc_platform.bigbrother.message_listener:
        class:  Ecommerce\EcommerceBundle\EventListener\PaysUpperCaseSubscriber
#        arguments:
#          - "@oc_platform.bigbrother.message_notificator"
#          - ["alexandre", "marine", "pierre"]
        tags:
          - { name: kernel.event_subscriber }

    entuty_media_service:
        class: Ecommerce\EcommerceBundle\Entity\Media
        arguments: ["%img_directory%"]

    send.mail.service:
        class: "%send.mail.service.class%"
        arguments: ["@mailer","@templating"]