language: php
php:
    - 5.6
    - 7.0.10
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

before_script:
  - composer install --dev --prefer-dist
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - phpunit -c var/
notifications:
  email:
    -  chabour.dev@gmail.com