fos_elastica:
    clients:
        default: { host: "%elastic_host%", port: "%elastic_port%" }
    indexes:
        mc_article:
            client: default
            types:
                article:
                    mappings:
                        id:
                            type: integer
                        createdAt :
                            type : date
                        publishedAt :
                            type : date
                        published :
                            type : boolean
                        title : ~
                        content : ~
                    persistence:
                        driver: orm
                        model: UserBundle\Entity\Article
                        finder: ~
                        provider: ~
                        listener: ~