pages_admin:
    resource: "@PagesBundle/Controller/Admin/PagesController.php"
    type:     annotation
produits_admin:
    resource: "@EcommerceBundle/Controller/Admin/ProduitsController.php"
    type:     annotation
categories_admin:
    resource: "@EcommerceBundle/Controller/Admin/CategoriesController.php"
    type:     annotation
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
pages:
    resource: "@PagesBundle/Controller/"
    type:     annotation
    prefix:   /
ecommerce:
    resource: "@EcommerceBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

