pages_pages:
    resource: "@PagesBundle/Controller/Admin/"
    type:     annotation
produits_admin:
    resource: "@EcommerceBundle/Controller/Admin/"
    type:     annotation
ecommerce_produits:
    resource: "@EcommerceBundle/Controller/ProduitsController.php"
    type:     annotation
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
pages:
    resource: "@PagesBundle/Controller/"
    type:     annotation
    prefix:   /
ecommerce:
    resource: "@EcommerceBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

