# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    guzzle.client.class: Guzzle\Service\Client

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    example.client:
        class: "%guzzle.client.class%"
        tags:
            - { name: guzzle.client }