<?php

namespace UserBundle\Repository;
use Doctrine\ORM\EntityRepository;
use UserBundle\Model\ArticleSearch;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    
}
