<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends \Doctrine\ORM\EntityRepository
{

    public function byFacture($utilisateur)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.utilisateur = :utilisateur')
            ->andWhere('c.valider = 1')
            ->andWhere('c.reference != 0')
            ->orderBy('c.id')
            ->setParameter('utilisateur', $utilisateur);

        return $qb->getQuery()->getResult();
    }
    
    public function byDateCommand($date)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.date > :date')
            ->andWhere('u.valider = 1')
            ->orderBy('u.id')
            ->setParameter('date', $date);
        
        return $qb->getQuery()->getResult();
    }
}
