<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('p')
            ->Select('p')
            ->Where('p.id IN (:array)')
            ->setParameter('array', $array);
        
        return $qb->getQuery()->getResult();
    }
    
    public function byCategorie($idCategorie)
    {
        $qb = $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.categorie = :categorie')
            ->andWhere('p.disponible = 1')
            ->orderBy('p.id')
            ->setParameter('categorie', $idCategorie);
        
        return $qb->getQuery()->getResult();
    }
    
    
    public function searchProductsbyStr($str)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.nom like :chaine')
            ->andWhere('u.disponible = 1')
            ->orderBy('u.id')
            ->setParameter('chaine', '%' . $str . '%');
        
        return $qb->getQuery()->getResult();
    }
}
