McMedia:
    type: entity
    table: mc_media
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        alt:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        path:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        updateAt:
            type: datetime
            nullable: true
            column: update_at
    lifecycleCallbacks: {  }
