McUtilisateursAdresses:
    type: entity
    table: mc_utilisateurs_adresses
    indexes:
        IDX_3A1EE7B1FB88E14F:
            columns:
                - utilisateur_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 125
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 125
            options:
                fixed: false
        telephone:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        adresse:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        cp:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        pays:
            type: string
            nullable: false
            length: 125
            options:
                fixed: false
        ville:
            type: string
            nullable: false
            length: 125
            options:
                fixed: false
        complement:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        utilisateur:
            targetEntity: FosUser
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                utilisateur_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
