Pages:
    type: entity
    table: pages
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        contenu:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
